hi def link ungramAlternation Statement
hi def link ungramComment Comment
hi def link ungramDelimiter Delimiter
hi def link ungramLabel Label
hi def link ungramOperator Operator
hi def link ungramOr Conditional
hi def link ungramQuote ungramDelimiter
hi def link ungramRepeat Repeat
hi def link ungramRule Identifier
hi def link ungramString String
hi def link ungramToken Type
