highlight link ungramAlternation ungramDelimiter
highlight link ungramConditional Conditional
highlight link ungramDelimiter Delimiter
highlight link ungramLabel Label
highlight link ungramOperator Operator
highlight link ungramQuote String
highlight link ungramRepeat Repeat
highlight link ungramRule Identifier
highlight link ungramString Constant
highlight link ungramToken Type
